before:
  hooks:
    - go mod download
    - go generate ./...
    # First run the opentelemetry-collector-builder
    - make -e VERSION="{{.Version}}" build
builds:
  - id: "jaeger-otel-agent"
    dir: ./builds/agent
    binary: "jaeger-otel-agent"
    flags:
      -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

  - id: "jaeger-otel-collector"
    dir: ./builds/collector
    binary: "jaeger-otel-collector"
    flags:
      -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      #amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
