name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Install tools
      run: make install-tools

    - name: Lint
      run: make lint

    - name: Build the distribution
      run: make build

    - name: Smoke tests
      env:
        LOGRUS_LEVEL: "debug"
        TEST_OPTIONS: "-v"
      run: ./.ci/run-e2e-tests.sh
